version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Reports suspicious constructs
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Advanced static analysis
    - unused         # Check for unused constants, variables, functions
    - misspell       # Find commonly misspelled words
    - gosec          # Security issues
    - bodyclose      # Check HTTP response body is closed
    - unconvert      # Detect unnecessary type conversions
    - unparam        # Detect unused function parameters
    - gocritic       # Diagnostics for bugs, performance and style
    - revive         # Fast, configurable, extensible linter
